tos:
    path: /pravidla-ochrany-osobnych-udajov
    controller: App\Controller\ArticleController::tos

unsubscribe:
    path: /unsubscribe/{hash}/{newsletterId}
    controller: App\Controller\HomepageController::unsubscribe

verify:
    path: /o/{hash}
    controller: App\Controller\HomepageController::verify

stats:
    path: /secret/d8y38s8d97tf7ad78949t7a/stats
    controller: App\Controller\StatsController::index

thank_you:
    path: /dakujeme/{slug}
    controller: App\Controller\ArticleController::thankYou
    defaults:
        slug: ''

list:
    path: /signatari/{slug}
    controller: App\Controller\HomepageController::list
    defaults:
        slug: ''

homepage:
    path: /{slug}
    controller: App\Controller\HomepageController::index
    defaults:
        slug: ''

#word_cloud:
#    path: /secret/d8y38s8d97tf7ad78949t7a/cloud
#    controller: App\Controller\StatsController::cloud
