homepage:
    path: /{version}
    controller: App\Controller\HomepageController::index
    defaults:
        version: 1
    requirements:
        version: '1|2|3|4|5'

tos:
    path: /pravidla-ochrany-osobnych-udajov
    controller: App\Controller\ArticleController::tos

thank_you:
    path: /dakujeme
    controller: App\Controller\ArticleController::thankYou

unsubscribe:
    path: /unsubscribe/{hash}/{newsletterId}
    controller: App\Controller\HomepageController::unsubscribe

verify:
    path: /o/{hash}
    controller: App\Controller\HomepageController::verify

list:
    path: /signatari
    controller: App\Controller\HomepageController::list

stats:
    path: /secret/d8y38s8d97tf7ad78949t7a/stats
    controller: App\Controller\StatsController::index

#word_cloud:
#    path: /secret/d8y38s8d97tf7ad78949t7a/cloud
#    controller: App\Controller\StatsController::cloud
