homepage:
    path: /{version}
    controller: App\Controller\HomepageController::index
    defaults:
        version: 1
    requirements:
        version: '1|2|3|4|5'

tos:
    path: /pravidla-ochrany-osobnych-udajov
    controller: App\Controller\ArticleController::tos

thank_you:
    path: /dakujeme
    controller: App\Controller\ArticleController::thankYou

verify:
    path: /o/{hash}
    controller: App\Controller\HomepageController::verify

list:
    path: /signatari
    controller: App\Controller\HomepageController::list
